# Generated by Django 5.1 on 2025-12-19 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_delete_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='lgbm_ranker_v1', max_length=64, unique=True)),
                ('model_blob', models.BinaryField()),
                ('feature_schema', models.JSONField(default=dict)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=8)),
                ('language', models.CharField(blank=True, default='', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titles', models.ManyToManyField(related_name='editorial_collections', to='users.title')),
            ],
        ),
        migrations.CreateModel(
            name='TitleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim', models.IntegerField(default=0)),
                ('vector', models.JSONField(default=list)),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='users.title')),
            ],
        ),
        migrations.CreateModel(
            name='TitleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('click', 'click'), ('outbound', 'outbound'), ('like', 'like'), ('dislike', 'dislike'), ('add_to_list', 'add_to_list'), ('not_interested', 'not_interested'), ('search_click', 'search_click')], max_length=32)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.title')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'action', '-created_at'], name='reco_titlea_profile_90f3ee_idx'), models.Index(fields=['title', 'action', '-created_at'], name='reco_titlea_title_i_771d9a_idx'), models.Index(fields=['session_id', 'action', '-created_at'], name='reco_titlea_session_ad6c7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TitleImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(blank=True, default='', max_length=64)),
                ('position', models.IntegerField(default=0)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=8)),
                ('device', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.title')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', '-created_at'], name='reco_titlei_profile_3e7ae8_idx'), models.Index(fields=['title', '-created_at'], name='reco_titlei_title_i_bd936f_idx'), models.Index(fields=['session_id', '-created_at'], name='reco_titlei_session_8e1445_idx')],
            },
        ),
        migrations.CreateModel(
            name='TitleSimilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', max_length=64)),
                ('similar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_in', to='users.title')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_out', to='users.title')),
            ],
            options={
                'indexes': [models.Index(fields=['title', '-score'], name='reco_titles_title_i_116e45_idx')],
                'unique_together': {('title', 'similar', 'model_name')},
            },
        ),
    ]
