# Generated by Django 5.1 on 2025-12-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleaction',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
