# Generated by Django 5.1 on 2025-12-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0002_alter_titleaction_provider'),
        ('users', '0010_actor_uniq_actor_per_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='titlesimilar',
            name='reco_titles_title_i_116e45_idx',
        ),
        migrations.AddIndex(
            model_name='titleembedding',
            index=models.Index(fields=['model_name', 'title'], name='reco_titlee_model_n_798c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='titlesimilar',
            index=models.Index(fields=['title', 'model_name', '-score'], name='reco_titles_title_i_1c953d_idx'),
        ),
    ]
