# Generated by Django 5.1 on 2025-12-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0003_remove_titlesimilar_reco_titles_title_i_116e45_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleembedding',
            name='vector_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
