# Generated by Django 5.1 on 2025-12-23 17:56

from django.db import migrations


def _index_exists(schema_editor, table_name: str, index_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(1)
            FROM INFORMATION_SCHEMA.STATISTICS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = %s
              AND INDEX_NAME = %s
            """,
            [table_name, index_name],
        )
        return (cursor.fetchone()[0] or 0) > 0


def _drop_index_if_exists(schema_editor, table_name: str, index_name: str) -> None:
    if _index_exists(schema_editor, table_name, index_name):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"DROP INDEX `{index_name}` ON `{table_name}`;")


def _create_index_if_missing(schema_editor, table_name: str, index_name: str, columns_sql: str) -> None:
    """
    columns_sql: like "`profile_id`, `created_at`" or "`model_name`, `title_id`, `score`"
    """
    if not _index_exists(schema_editor, table_name, index_name):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"CREATE INDEX `{index_name}` ON `{table_name}` ({columns_sql});")


def forwards(apps, schema_editor):
    TitleSimilar = apps.get_model("reco", "TitleSimilar")
    TitleAction = apps.get_model("reco", "TitleAction")

    ts_table = TitleSimilar._meta.db_table       # usually reco_titlesimilar
    ta_table = TitleAction._meta.db_table        # usually reco_titleaction

    # 1) Safe DROP (was failing earlier)
    _drop_index_if_exists(schema_editor, ts_table, "reco_titles_title_i_1c953d_idx")

    # 2) Safe ADDs (now failing due to duplicates)
    # NOTE: column names in DB are usually "<field>_id" for FKs (profile_id, title_id, similar_id)
    _create_index_if_missing(
        schema_editor,
        ta_table,
        "reco_titlea_profile_acf144_idx",
        "`profile_id`, `created_at`",
    )
    _create_index_if_missing(
        schema_editor,
        ta_table,
        "reco_titlea_profile_723c16_idx",
        "`profile_id`, `title_id`",
    )
    _create_index_if_missing(
        schema_editor,
        ts_table,
        "reco_titles_model_n_ec6621_idx",
        "`model_name`, `title_id`, `score`",
    )
    _create_index_if_missing(
        schema_editor,
        ts_table,
        "reco_titles_model_n_087cfc_idx",
        "`model_name`, `similar_id`",
    )


def backwards(apps, schema_editor):
    TitleSimilar = apps.get_model("reco", "TitleSimilar")
    TitleAction = apps.get_model("reco", "TitleAction")
    ts_table = TitleSimilar._meta.db_table
    ta_table = TitleAction._meta.db_table

    # Safe drops for rollback
    _drop_index_if_exists(schema_editor, ta_table, "reco_titlea_profile_acf144_idx")
    _drop_index_if_exists(schema_editor, ta_table, "reco_titlea_profile_723c16_idx")
    _drop_index_if_exists(schema_editor, ts_table, "reco_titles_model_n_ec6621_idx")
    _drop_index_if_exists(schema_editor, ts_table, "reco_titles_model_n_087cfc_idx")


class Migration(migrations.Migration):

    dependencies = [
        ("reco", "0004_titleembedding_vector_blob"),
        ("users", "0011_title_primary_genre_norm"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
