# Generated by Django 5.1 on 2025-12-29 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0005_remove_titlesimilar_reco_titles_title_i_1c953d_idx_and_more'),
        ('users', '0011_title_primary_genre_norm'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoHomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_version', models.CharField(db_index=True, default='home_v1', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='titlesimilar',
            name='reco_titles_title_i_1c953d_idx',
        ),
        migrations.AddIndex(
            model_name='titleaction',
            index=models.Index(fields=['profile', '-created_at'], name='reco_titlea_profile_acf144_idx'),
        ),
        migrations.AddIndex(
            model_name='titleaction',
            index=models.Index(fields=['profile', 'title'], name='reco_titlea_profile_723c16_idx'),
        ),
        migrations.AddIndex(
            model_name='titlesimilar',
            index=models.Index(fields=['model_name', 'title', '-score'], name='reco_titles_model_n_ec6621_idx'),
        ),
        migrations.AddIndex(
            model_name='titlesimilar',
            index=models.Index(fields=['model_name', 'similar'], name='reco_titles_model_n_087cfc_idx'),
        ),
        migrations.AddField(
            model_name='recohomesnapshot',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_snapshot', to='users.profile'),
        ),
        migrations.AddIndex(
            model_name='recohomesnapshot',
            index=models.Index(fields=['algo_version', 'expires_at'], name='reco_recoho_algo_ve_39bce5_idx'),
        ),
    ]
