# Generated by Django 5.1 on 2025-12-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0006_recohomesnapshot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecoHomeSnapshot',
        ),
    ]
