# Generated by Django 5.1 on 2025-12-29 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0007_delete_recohomesnapshot'),
        ('users', '0011_title_primary_genre_norm'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoHomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_version', models.CharField(db_index=True, default='home_v1', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_snapshot', to='users.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['algo_version', 'expires_at'], name='reco_recoho_algo_ve_39bce5_idx')],
            },
        ),
    ]
