# Generated by Django 5.1 on 2025-09-30 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('season_number', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('overview', models.TextField(blank=True, default='')),
                ('air_date', models.CharField(blank=True, default='', max_length=10)),
                ('poster', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], db_index=True, default='movie', max_length=10)),
                ('imdb_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, default='', max_length=255)),
                ('original_language', models.CharField(blank=True, default='', max_length=8)),
                ('release_date', models.CharField(blank=True, default='', max_length=10)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('first_air_date', models.CharField(blank=True, default='', max_length=10)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('rating', models.CharField(blank=True, default='', max_length=10)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, default='')),
                ('landscape_image', models.URLField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='')),
                ('movie_link2', models.URLField(blank=True, default='')),
                ('movie_link3', models.URLField(blank=True, default='')),
                ('trailer_url', models.URLField(blank=True, default='')),
                ('trailer_clip_url', models.URLField(blank=True, default='')),
                ('genre', models.CharField(blank=True, default='', max_length=255)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('production_companies', models.JSONField(blank=True, default=list)),
                ('production_countries', models.JSONField(blank=True, default=list)),
                ('spoken_languages', models.JSONField(blank=True, default=list)),
                ('belongs_to_collection', models.JSONField(blank=True, null=True)),
                ('director', models.CharField(blank=True, default='', max_length=255)),
                ('cast', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('plan_type', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField(default=1)),
                ('exp_year', models.IntegerField(default=2025)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age_restriction', models.CharField(max_length=10)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('language_preference', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('episode_number', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('overview', models.TextField(blank=True, default='')),
                ('air_date', models.CharField(blank=True, default='', max_length=10)),
                ('still_path', models.CharField(blank=True, default='', max_length=300)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('imdb_code', models.CharField(blank=True, max_length=20, null=True)),
                ('video_url', models.URLField(blank=True, default='')),
                ('episode_link2', models.URLField(blank=True, default='')),
                ('episode_link3', models.URLField(blank=True, default='')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='users.season')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100)),
                ('plan_type', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('is_trial', models.BooleanField(default=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TVShowExtras',
            fields=[
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tv_extras', serialize=False, to='users.title')),
                ('number_of_seasons', models.IntegerField(default=0)),
                ('number_of_episodes', models.IntegerField(default=0)),
                ('in_production', models.BooleanField(default=False)),
                ('episode_run_time', models.JSONField(blank=True, default=list)),
                ('network_names', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['type', 'popularity'], name='users_title_type_32a681_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['type', 'vote_average'], name='users_title_type_c77c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['title'], name='users_title_title_16cc72_idx'),
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.UniqueConstraint(fields=('type', 'tmdb_id'), name='uniq_title_type_tmdbid'),
        ),
        migrations.AddField(
            model_name='season',
            name='tv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='users.title'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'episode_number')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('tv', 'season_number')},
        ),
    ]
