# Generated by Django 5.1 on 2025-09-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
    ]
