# Generated by Django 5.1 on 2025-12-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_link4',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_link5',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_link6',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='title',
            name='movie_link4',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='title',
            name='movie_link5',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='title',
            name='movie_link6',
            field=models.URLField(blank=True, default=''),
        ),
    ]
