# Generated by Django 5.1 on 2025-12-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_episode_episode_link4_episode_episode_link5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_link4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_link5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_link6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='title',
            name='movie_link4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='title',
            name='movie_link5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='title',
            name='movie_link6',
            field=models.TextField(blank=True, default=''),
        ),
    ]
