# Generated by Django 5.1 on 2025-12-22 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_episode_episode_link4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_norm', models.CharField(db_index=True, max_length=120)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors_rel', to='users.title')),
            ],
            options={
                'indexes': [models.Index(fields=['name_norm', 'title'], name='users_title_name_no_d90bca_idx'), models.Index(fields=['title'], name='users_title_title_i_281062_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'name_norm'), name='uniq_title_actor')],
            },
        ),
        migrations.CreateModel(
            name='TitleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_norm', models.CharField(db_index=True, max_length=160)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_rel', to='users.title')),
            ],
            options={
                'indexes': [models.Index(fields=['company_norm', 'title'], name='users_title_company_90ae15_idx'), models.Index(fields=['title'], name='users_title_title_i_905123_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'company_norm'), name='uniq_title_company')],
            },
        ),
        migrations.CreateModel(
            name='TitleCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_rel', to='users.title')),
            ],
            options={
                'indexes': [models.Index(fields=['country_code', 'title'], name='users_title_country_cdca37_idx'), models.Index(fields=['title'], name='users_title_title_i_762b44_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'country_code'), name='uniq_title_country')],
            },
        ),
        migrations.CreateModel(
            name='TitleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_norm', models.CharField(db_index=True, max_length=120)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords_rel', to='users.title')),
            ],
            options={
                'indexes': [models.Index(fields=['keyword_norm', 'title'], name='users_title_keyword_df06a2_idx'), models.Index(fields=['title'], name='users_title_title_i_d42e41_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'keyword_norm'), name='uniq_title_keyword')],
            },
        ),
        migrations.CreateModel(
            name='TitleNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_norm', models.CharField(db_index=True, max_length=160)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks_rel', to='users.title')),
            ],
            options={
                'indexes': [models.Index(fields=['network_norm', 'title'], name='users_title_network_069265_idx'), models.Index(fields=['title'], name='users_title_title_i_185674_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'network_norm'), name='uniq_title_network')],
            },
        ),
    ]
