# Generated by Django 5.1 on 2025-12-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_titleactor_titlecompany_titlecountry_titlekeyword_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='title',
            name='users_title_type_32a681_idx',
        ),
        migrations.RemoveIndex(
            model_name='title',
            name='users_title_type_c77c5d_idx',
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['type', 'popularity', 'vote_average', 'id'], name='users_title_type_a67505_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['type', 'release_year'], name='users_title_type_08bb47_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['original_title'], name='users_title_origina_c6fe50_idx'),
        ),
    ]
