# Generated by Django 5.1 on 2025-12-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_title_users_title_type_32a681_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleactor',
            name='profile_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titleactor',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
