# Generated by Django 5.1 on 2025-12-23 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_titleactor_profile_path_titleactor_tmdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_norm', models.CharField(db_index=True, max_length=255)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('profile_path', models.CharField(blank=True, max_length=255, null=True)),
                ('character', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='users.title')),
            ],
        ),
        migrations.DeleteModel(
            name='TitleActor',
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['name_norm'], name='users_actor_name_no_bab99f_idx'),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['tmdb_id'], name='users_actor_tmdb_id_c8f4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['title', 'name_norm'], name='users_actor_title_i_97db16_idx'),
        ),
    ]
