# Generated by Django 5.1 on 2025-12-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_actor_delete_titleactor_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(fields=('title', 'name_norm'), name='uniq_actor_per_title'),
        ),
    ]
