# Generated by Django 5.1 on 2025-12-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_actor_uniq_actor_per_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='primary_genre_norm',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
